# per https://docs.snyk.io/tutorials/github/securing-a-toolchain-with-snyk-and-github/part-2-container/section-1-containerize-your-app
name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag docker-goof
    - name: Snyk Container Test
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: docker-goof
        args: --severity-threshold=high
    - name: Upload Container Scan results to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif
